
export const DANH_MUC = {
    DONG_HO: 1,
    TRANG_SUC: 2,
    SAN_PHAM_CHIET_KHAU_CAO:3,
    THOI_TRANG_NU : 4,
    DIEN_THOAI : 5,
    PHU_KIEN : 6,
    THE_THAO_DU_LICH : 7,
    THOI_TRANG_NAM : 8,
    SACH:9,
    DO_DIEN_TU:10,
    THOI_TRANG_TRE_EM:11,
    TUI_VI:12,
    GIAY_DEP:13,
    BAO_HIEM:14,
    THIET_BI_GIA_DUNG:15,
    UU_DAI:16,
    CAMERA:17,
    CHAM_SOC_NHA_CUA:18
}
export const PAGINATION = {
    PAGE_SIZE : 10
};